/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#f7f9fb',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#b8c4ff',
        'inverse-surface': '#2d3133',
        'on-background': '#191c1e',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'on-primary-container': '#a8b8ff',
        'on-primary-fixed': '#001453',
        'on-primary-fixed-variant': '#173bab',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#007233',
        'on-secondary-fixed': '#00210a',
        'on-secondary-fixed-variant': '#005323',
        'on-surface': '#191c1e',
        'on-surface-variant': '#444653',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffa583',
        'on-tertiary-fixed': '#380d00',
        'on-tertiary-fixed-variant': '#802a00',
        outline: '#757684',
        'outline-variant': '#c4c5d5',
        primary: '#00288e',
        'primary-container': '#1e40af',
        'primary-fixed': '#dde1ff',
        'primary-fixed-dim': '#b8c4ff',
        secondary: '#006d30',
        'secondary-container': '#92f5a4',
        'secondary-fixed': '#95f8a7',
        'secondary-fixed-dim': '#79db8d',
        surface: '#f7f9fb',
        'surface-bright': '#f7f9fb',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'surface-container-low': '#f2f4f6',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#d8dadc',
        'surface-tint': '#3755c3',
        'surface-variant': '#e0e3e5',
        tertiary: '#611e00',
        'tertiary-container': '#872d00',
        'tertiary-fixed': '#ffdbce',
        'tertiary-fixed-dim': '#ffb59a',
      },
      fontFamily: {
        sans: ['"Public Sans"', 'system-ui', '-apple-system', 'sans-serif'],
      },
      animation: {
        marquee: 'marquee 20s linear infinite',
        'bounce-slow': 'bounce-slow 4s infinite ease-in-out',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(-100%)' },
        },
        'bounce-slow': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-20px)' },
        },
      },
    },
  },
  plugins: [],
};